name = "booleans"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-10-02"

[build]
command = "yarn build:worker"

[build.upload]
format = "service-worker"
